# 16S rRNA sequencing

This is the workflow of analysing the 16S rRNA sequencing of the 18 samples. I have followed Qiime2 analysis workflow: <https://amplicon-docs.qiime2.org/en/stable/>.

## Directory structure (What files and where they are)

```         
16S_project/
│
├── sample-metadata.tsv                   # Sample metadata (experimental variables)
├── manifest.tsv                          # Raw paired-end FASTQ manifest
|
├── Fastq/                                # Raw data
│   ├── Fiber1_S4_L001_R1_001.fastq.gz           
│   ├── Fiber1_S4_L001_R2_001.fastq.gz 
│   └── ...
|
├── 5_strains/
│   ├── 5_strains_refseqs.fasta           # Reference sequences of the 5 strains
│   ├── taxonomy.tsv                      # Reference taxonomy table for the 5 strains
│   ├── refs.qza                          # Imported reference sequences (QIIME2 artifact)
│   ├── taxonomy.qza                      # Imported taxonomy artifact
│   ├── refs-v3v4.qza                     # Extracted V3-V4 region for classifier
│   └── 5strain-classifier.qza            # Trained naive-bayes classifier
│
├── results/
│   ├── demux.qza                         # Imported raw sequences (paired-end)
│   ├── demux.qzv                         # Visualization of demultiplexed reads
│   ├── trimmed-seqs.qza                  # Primer-trimmed sequences
│   ├── trimmed-seqs.qzv                  # Visualization of trimmed reads
│   ├── asv-seqs.qza                      # DADA2 representative sequences
│   ├── asv-table.qza                     # DADA2 feature table (counts)
│   ├── denoising-stats.qza               # DADA2 stats
│   ├── denoising-stats.qzv               # Visualization of denoising stats
│   ├── asv-frequencies.qza               # ASV frequency table
│   ├── sample-frequencies.qza            # Sample frequency table
│   ├── asv-seqs.qzv                      # Visualization of representative ASVs
|
│   ├── taxonomy.qza                      # ASV taxonomy assigned by classifier
│   ├── taxonomy.qzv                      # Visualization of taxonomy
│   ├── barplot.qzv                       # Barplot
│
│   ├── g-table.qza                       # ASVs filtered to genus-level (g__)
│   ├── g-table.qzv                       # Visualization of collapsed genus table
│   ├── g-feature-frequencies.qza         # Genus-level feature frequencies
│   └── g-sample-frequencies.qza          # Genus-level sample frequencies
|
```

## QIIME 2 Amplicon Analysis Step-By-Step Guide

Version 2026.1

View files: <https://view.qiime2.org/>

### Import raw paired-end sequences

`manifest.tsv` listing sample FASTQ files.

``` bash
qiime tools import \
  --type 'SampleData[PairedEndSequencesWithQuality]' \
  --input-path manifest.tsv \
  --input-format PairedEndFastqManifestPhred33V2 \
  --output-path results/demux.qza

# Inspecting quality of the raw reads
qiime demux summarize \
  --i-data results/demux.qza \
  --o-visualization results/demux.qzv
```

### Trim primers with Cutadapt

Removes forward and reverse primers. **NOTE**: primers had already been removed, so no change from the raw data, thus further `demux.qza` was used.

``` bash
qiime cutadapt trim-paired \
  --i-demultiplexed-sequences results/demux.qza \
  --p-front-f CCTACGGGNGGCWGCAG \
  --p-front-r GACTACHVGGGTATCTAATCC \
  --o-trimmed-sequences results/trimmed-seqs.qza

# Inspecting quality of reads after trimming
qiime demux summarize \
  --i-data results/trimmed-seqs.qza \
  --o-visualization results/trimmed-seqs.qzv
```

### DADA2: Denoise sequences and generate ASVs

Since Sequencing was performed on an Illumina MiSeq platform using a Nano 2 × 250 bp paired-end protocol, 250 bp is the length to truncate.

``` bash
qiime dada2 denoise-paired \
  --i-demultiplexed-seqs results/demux.qza \
  --p-trim-left-f 0 \
  --p-trunc-len-f 250 \
  --p-trim-left-r 0 \
  --p-trunc-len-r 250 \
  --p-n-threads 4 \
  --o-representative-sequences results/asv-seqs.qza \
  --o-table results/asv-table.qza \
  --o-denoising-stats results/denoising-stats.qza \
  --o-base-transition-stats results/base-transition-stats.qza

# Check DADA2 statistics
qiime metadata tabulate \
  --m-input-file results/denoising-stats.qza \
  --o-visualization results/denoising-stats.qzv
```

### Summarize feature table and ASVs

Inspect read counts per ASV and sample.

``` bash
qiime feature-table summarize \
  --i-table results/asv-table.qza \
  --m-metadata-file sample-metadata.tsv \
  --o-summary results/asv-table.qzv \
  --o-sample-frequencies results/sample-frequencies.qza \
  --o-feature-frequencies results/asv-frequencies.qza

qiime feature-table tabulate-seqs \
  --i-data results/asv-seqs.qza \
  --m-metadata-file results/asv-frequencies.qza \
  --o-visualization results/asv-seqs.qzv
```

## **QIIME 2: Taxonomy Classifier Workflow**

A Naive Bayes classifier was used for taxonomic assignment. The reference sequences were first trimmed to include only the region corresponding to the portion of the 16S rRNA gene sequenced in this analysis — specifically the V3–V4 region amplified by the 515F/806R primer pair. The trained classifier was then applied to the sequence data to assign taxonomy.

#### **Reference Sequences (5 Strains)**

The 16S rRNA gene reference sequences for the target strains were obtained from NCBI - Bacterial 16S Ribosomal RNA RefSeq Targeted Loci Project on `09/02/2026` - 09 February 2026. The following reference sequences were used:

| Strain | NCBI Reference Sequence |
|----|----|
| *Bifidobacterium longum* subsp. *infantis* ATCC 15697 | NR_043437.1 |
| *Bifidobacterium adolescentis* ATCC 15703 | NR_074802.2 |
| *Roseburia hominis* A2-183 | NR_042008.1 |
| *Roseburia intestinalis* L1-82 | NR_027557.1 |
| *Roseburia inulinivorans* DSM 16841 A2-194 | NR_042007.1 |

``` bash
# Import reference sequences for classifier
qiime tools import \
  --type 'FeatureData[Sequence]' \
  --input-path 5_strains/5_strains_refseqs.fasta \
  --output-path 5_strains/refs.qza

# Import feference taxonomy table for the 5 strains
qiime tools import \
  --type 'FeatureData[Taxonomy]' \
  --input-path 5_strains/taxonomy.tsv \
  --output-path 5_strains/taxonomy.qza

# Extract V3-V4 region from the reference sequences
qiime feature-classifier extract-reads \
  --i-sequences 5_strains/refs.qza \
  --p-f-primer CCTACGGGNGGCWGCAG \
  --p-r-primer GACTACHVGGGTATCTAATCC \
  --p-trunc-len 0 \
  --o-reads 5_strains/refs-v3v4.qza

# Train Naive-Bayes classifier 
qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads 5_strains/refs-v3v4.qza \
  --i-reference-taxonomy 5_strains/taxonomy.qza \
  --o-classifier 5_strains/5strain-classifier.qza

# Assign taxonomy to the ASVs
qiime feature-classifier classify-sklearn \
  --i-classifier 5_strains/5strain-classifier.qza \
  --i-reads results/asv-seqs.qza \
  --o-classification results/taxonomy.qza

# Check the assigned taxonomy
qiime metadata tabulate \
  --m-input-file results/taxonomy.qza \
  --o-visualization results/taxonomy.qzv

# Removing the reads only assigned to 'Bacteria'
qiime taxa filter-table \
  --i-table results/asv-table.qza \
  --i-taxonomy results/taxonomy.qza \
  --p-include p__ \
  --o-filtered-table results/asv-table2.qza

qiime feature-table summarize \
  --i-table results/asv-table2.qza \
  --m-metadata-file sample-metadata.tsv \
  --o-summary results/asv-table2.qzv \
  --o-sample-frequencies results/sample-frequencies2.qza \
  --o-feature-frequencies results/asv-frequencies2.qza

# Barplot
qiime taxa barplot \
  --i-table results/asv-table2.qza \
  --i-taxonomy results/taxonomy.qza \
  --m-metadata-file sample-metadata.tsv \
  --o-visualization results/barplot.qzv
```

ASVs classified only at the kingdom level (k\_\_Bacteria) were removed prior to taxonomic collapsing. In the context of a synthetic microbial community composed exclusively of known bacterial strains, such assignments likely reflect low-quality or non-informative sequences and do not represent biologically meaningful taxa.

### Filtering on genus level

``` bash
qiime taxa filter-table \
  --i-table results/asv-table.qza \
  --i-taxonomy results/taxonomy.qza \
  --p-include g__ \
  --o-filtered-table results/g-table.qza

qiime feature-table summarize \
  --i-table results/g-table.qza \
  --m-metadata-file sample-metadata.tsv \
  --o-summary results/g-table.qzv \
  --o-feature-frequencies results/g-feature-frequencies.qza \
  --o-sample-frequencies results/g-sample-frequencies.qza
  
qiime taxa barplot \
  --i-table results/g-table.qza \
  --i-taxonomy results/taxonomy.qza \
  --m-metadata-file sample-metadata.tsv \
  --o-visualization results/g-barplot.qzv
```

### Exporting files for downstream analysis

if you ever need to export the files created by qiime, use the following command. Otherwise by uploading the qiime file to <https://view.qiime2.org/>, you can download it from there.

``` bash
# Export genus-level feature table
qiime tools export \
  --input-path results/g-table.qza \
  --output-path exported/genus
```

## Relative abundance barplot

The CSV file is extracted from the genus barplot created by qiime. The numbers correspond to the number of reads/sequences that have been assign to the genus in that respective column. the CSV file is named `level-6.csv`. How the csv file looks:

```         
index,k__Bacteria;p__Actinobacteriota;c__Actinobacteria;o__Bifidobacteriales;f__Bifidobacteriaceae;g__Bifidobacterium,k__Bacteria;p__Firmicutes;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Roseburia,name,group
S10,10801.0,3893.0,GLC3,Glucose
S11,7523.0,2933.0,HMO3,HMO
S12,721.0,11885.0,Fiber3,Fiber
S13,6616.0,6260.0,MIX3,Mix
S14,9387.0,4500.0,GLC4,Glucose
S15,5698.0,2801.0,HMO4,HMO
S16,974.0,11948.0,Fiber4,Fiber
S17,801.0,12837.0,Mix4,Mix
S1,8903.0,3315.0,Zero,Control
S2,9078.0,2979.0,Glc1,Glucose
S3,6274.0,5000.0,HMO1,HMO
S4,794.0,8840.0,Fiber1,Fiber
S5,6225.0,5102.0,Mix1,Mix
S6,9799.0,3666.0,Glc2,Glucose
S7,7647.0,4078.0,HMO2,HMO
S8,194.0,9181.0,Fiber2,Fiber
S9,737.0,11266.0,Mix2,Mix
```

The barplot created by qiime can be viewed on <https://view.qiime2.org/>, by uploading the barplot file found in the results folder `g-barplot.qzv`.

```{r}
########### Genus ###########
library(tidyverse)

# read file
df6 <- read.csv("level-6.csv", check.names = FALSE)

# Renaming to the column names for proper naming
names(df6)[2] <- "Bifidobacterium"
names(df6)[3] <- "Roseburia"
names(df6)[4] <- "Step"
names(df6)[5] <- "Medium"

# Renamning the steps
df6 <- df6 %>%
  mutate(Step = recode(Step, "Mix1" = "HMO 1","Mix2" = "Fiber 2","MIX3" = "HMO 3","Mix4" = "Fiber 4", 'Zero' = ' ',
                       "Fiber1" = "1", "Fiber2" = "2", "Fiber3" = "3", 
                       "Fiber4" = "4", "Glc1" = "1", "Glc2" = "2", "GLC3" = "3",
                       "GLC4" = "4", "HMO1" = "1", "HMO2" = "2", "HMO3" = "3",
                       "HMO4" = "4"),
         Medium = recode(Medium, 'Control' = ' ', 'Mix' = 'Alternating'))

# Convert to long format
df6_long <- df6 %>%
  pivot_longer(
    cols = -c(index, Step, Medium),   # keep metadata columns
    names_to = "Genus",
    values_to = "abundance"
  )

df6_long <- df6_long %>%
  group_by(index) %>%
  mutate(rel_abundance = abundance / sum(abundance),
         percent = round(rel_abundance * 100,0))

# colours for the two genera 
my.colors <- c('#BEAED4', '#FDC086')

# if colours want to be added to the different mediums
medium_colors <- c(
  ' ' = '#515151',
  "Glucose"    = "#515151",
  "HMO"       = "#C03830",
  "Fiber"      = "#008835",
  "Alternating"= "#317EC2"
)

# specifying the order
df6_long$Medium <- factor(df6_long$Medium,
                          levels = c(" ", "Glucose", "HMO", "Fiber",
                                     "Alternating"))

df6_long$Genus <- factor(df6_long$Genus,
                          levels = c("Roseburia", "Bifidobacterium"))

df6_long$Step <- factor(df6_long$Step,
                        levels = c(' ', '1', '2', '3', '4', 'HMO 1', 
                                   'Fiber 2', 'HMO 3', 'Fiber 4'))


# creating the barplot
ggplot(data = df6_long, aes( x = rel_abundance, y = Step)) +
  
  facet_wrap(~ Medium , scales = "free_y", space = "free_y", 
             strip.position = "left") +
  
  geom_bar(aes(fill = Genus), stat = "identity", position = "stack") +
  geom_text(aes(label=paste0(percent,"%")),
                     position=position_stack(vjust=0.5), colour="white", 
            hjust = -0.001) +
  
  scale_y_discrete(limits = rev) +
  scale_x_continuous(name = "Relative abundance", labels = scales::percent,
                     position = "top") +
  scale_fill_manual(name = 'Genus', values = my.colors) +
  
  labs(y = ' ') +
  
  theme(panel.background = element_blank(),
        
        axis.text.x = element_text(size = 10),
        axis.ticks.y = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.title.x.top = element_text(size = 12),
        axis.title.y = element_text(angle = 0, vjust = 1, hjust = -1),
        
        legend.text = element_text(size = 10, face = 'italic'),
        legend.title = element_text(size = 12, face = 'bold'),
        legend.position = "top",
        legend.direction = "horizontal",
        
        strip.text = element_text(angle = 0, face = "bold", size = 12),
        strip.placement = "outside",
        strip.background = element_blank(),
        
        plot.margin = margin(10, 15, 10, 10)) +
  
  coord_cartesian(expand = FALSE, clip = 'off')

# saving the plot
ggsave("rel_abundance.pdf",
       plot = last_plot(),
       width = 21,
       height = 14.85,
       units = "cm",
       dpi = 300)


```
